apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: neuralq

images:
  - name: ghcr.io/harshsharma00109/neuralq-backend
    newTag: "BACKEND_IMAGE_TAG"
  - name: ghcr.io/harshsharma00109/neuralq-worker
    newTag: "WORKER_IMAGE_TAG"
  - name: ghcr.io/harshsharma00109/neuralq-frontend
    newTag: "FRONTEND_IMAGE_TAG"