apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: neuralq

patchesStrategicMerge:
  - backend-patch.yaml
  - worker-patch.yaml

images:
  - name: ghcr.io/YOUR_ORG/neuralq-backend
    newTag: "3507a480"   # replaced by CI/CD
  - name: ghcr.io/YOUR_ORG/neuralq-worker
    newTag: "3507a480"
  - name: ghcr.io/YOUR_ORG/neuralq-frontend
    newTag: "3507a480"
