apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: neuralq
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
