apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: neuralq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/harshsharma00109/neuralq-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              value: "mongodb://mongo-0.mongo-service:27017/ai_task_platform"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_SECRET
              value: "MyStr0ngS3cr3tKey2024NeuralQ!"
            - name: JWT_EXPIRES_IN
              value: "7d"
