apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: neuralq
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/harshsharma00109/neuralq-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: MONGODB_URI
              value: "mongodb://mongo-service:27017/ai_task_platform"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_SECRET
              value: "MyStr0ngS3cr3tKey2024NeuralQ!"
            - name: JWT_EXPIRES_IN
              value: "7d"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: neuralq
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
