apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: neuralq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/harshsharma00109/neuralq-worker:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: MONGODB_URI
              value: "mongodb://mongo-service:27017/ai_task_platform"
            - name: WORKER_CONCURRENCY
              value: "5"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
